// Language Lab Free — V5.3 cloud progress sync
(function(){
  const STORAGE_KEY='languageLabFreeV3';
  const cloud=window.LANGUAGE_LAB_SUPABASE||{};
  const client=cloud.client||null;
  let user=null,syncing=false,queued=false,initializedFor=null,lastSnapshot='',timer=null;
  function readLocal(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{}}catch{return {}}}
  function writeLocal(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));try{if(typeof state!=='undefined')state=data;}catch{}}
  function langDefaults(v={}){return {mastery:{},writes:0,quizCorrect:0,quizTotal:0,favorites:[],xp:0,...v,mastery:{...(v.mastery||{})},favorites:[...(v.favorites||[])]};}
  function localDate(){const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const x=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${x.year}-${x.month}-${x.day}`;}
  function maxDate(a,b){return !a?b:!b?a:(a>b?a:b)}
  function mergeMastery(a={},b={}){const out={...a};for(const [k,v] of Object.entries(b))out[k]=Math.max(Number(out[k]||0),Number(v||0));return out;}
  function union(a=[],b=[]){return [...new Set([...(a||[]),...(b||[])])];}
  function setStatus(text,kind=''){let el=document.getElementById('cloudSyncStatus');if(!el){const top=document.querySelector('.top-actions');if(!top)return;el=document.createElement('span');el.id='cloudSyncStatus';el.className='cloud-sync-status';const account=document.getElementById('authAccountBtn');account?top.insertBefore(el,account):top.appendChild(el);}el.textContent=text;el.dataset.state=kind;el.title=text;}
  function injectStyle(){if(document.getElementById('cloudSyncStyle'))return;const s=document.createElement('style');s.id='cloudSyncStyle';s.textContent=`.cloud-sync-status{font-size:11px;font-weight:800;color:#64748b;white-space:nowrap}.cloud-sync-status[data-state="ok"]{color:#15803d}.cloud-sync-status[data-state="busy"]{color:#2563eb}.cloud-sync-status[data-state="error"]{color:#b45309}@media(max-width:560px){.cloud-sync-status{display:none}}`;document.head.appendChild(s);}
  function refreshUI(){try{if(typeof renderTop==='function')renderTop();if(typeof renderLanguages==='function')renderLanguages();if(typeof renderProgress==='function'&&document.getElementById('progressTab')?.classList.contains('active'))renderProgress();}catch(e){console.debug('[Language Lab Free] UI refresh skipped',e)}}
  function localHasProgress(s){return Number(s.xp||0)>0||Object.values(s.languages||{}).some(v=>Number(v.xp||0)>0||Number(v.writes||0)>0||Number(v.quizTotal||0)>0||Object.keys(v.mastery||{}).length||v.favorites?.length);}
  async function fetchCloud(){const [p,l,a]=await Promise.all([client.from('profiles').select('id,total_xp,current_streak,longest_streak,last_study_date,selected_language,timezone').eq('id',user.id).maybeSingle(),client.from('language_progress').select('language_code,current_unit,current_lesson,mastery,favorites,writing_attempts,quiz_correct,quiz_total,xp,updated_at').eq('user_id',user.id),client.from('study_activity').select('activity_date,xp_earned,study_minutes').eq('user_id',user.id).order('activity_date',{ascending:false}).limit(60)]);for(const r of [p,l,a])if(r.error)throw r.error;return {profile:p.data,languages:l.data||[],activity:a.data||[]};}
  function mergeCloudIntoLocal(local,remote){const out={selected:local.selected||remote.profile?.selected_language||'ja',xp:Number(local.xp||0),streak:Number(local.streak||1),lastStudy:local.lastStudy||null,languages:{...(local.languages||{})}};const p=remote.profile;if(p){out.xp=Math.max(out.xp,Number(p.total_xp||0));out.streak=Math.max(out.streak,Number(p.current_streak||0));out.lastStudy=maxDate(out.lastStudy,p.last_study_date);if(!localHasProgress(local)&&p.selected_language)out.selected=p.selected_language;}for(const r of remote.languages){const l=langDefaults(out.languages[r.language_code]);out.languages[r.language_code]={...l,mastery:mergeMastery(l.mastery,r.mastery||{}),favorites:union(l.favorites,r.favorites||[]),writes:Math.max(Number(l.writes||0),Number(r.writing_attempts||0)),quizCorrect:Math.max(Number(l.quizCorrect||0),Number(r.quiz_correct||0)),quizTotal:Math.max(Number(l.quizTotal||0),Number(r.quiz_total||0)),xp:Math.max(Number(l.xp||0),Number(r.xp||0)),currentUnit:Math.max(Number(l.currentUnit||0),Number(r.current_unit||0)),currentLesson:Math.max(Number(l.currentLesson||0),Number(r.current_lesson||0))};}return out;}
  async function pushState(s,remote){const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',today=localDate();const profile={id:user.id,total_xp:Number(s.xp||0),current_streak:Number(s.streak||0),longest_streak:Math.max(Number(remote.profile?.longest_streak||0),Number(s.streak||0)),last_study_date:s.lastStudy||null,selected_language:s.selected||'ja',timezone};const {error:pe}=await client.from('profiles').upsert(profile,{onConflict:'id'});if(pe)throw pe;const rows=Object.entries(s.languages||{}).map(([code,v])=>({user_id:user.id,language_code:code,current_unit:Number(v.currentUnit||0),current_lesson:Number(v.currentLesson||0),mastery:v.mastery||{},favorites:v.favorites||[],writing_attempts:Number(v.writes||0),quiz_correct:Number(v.quizCorrect||0),quiz_total:Number(v.quizTotal||0),xp:Number(v.xp||0)}));if(rows.length){const {error}=await client.from('language_progress').upsert(rows,{onConflict:'user_id,language_code'});if(error)throw error;}if(s.lastStudy===today){const previousDays=(remote.activity||[]).filter(x=>x.activity_date!==today).reduce((sum,x)=>sum+Number(x.xp_earned||0),0);const earnedToday=Math.max(0,Number(s.xp||0)-previousDays);const current=(remote.activity||[]).find(x=>x.activity_date===today);const {error:ae}=await client.from('study_activity').upsert({user_id:user.id,activity_date:today,xp_earned:Math.max(Number(current?.xp_earned||0),earnedToday),study_minutes:Number(current?.study_minutes||0)},{onConflict:'user_id,activity_date'});if(ae)throw ae;}}
  async function sync(reason='change'){if(!client||!user)return;if(syncing){queued=true;return;}syncing=true;queued=false;setStatus('⟳ Syncing','busy');try{const remote=await fetchCloud();const merged=mergeCloudIntoLocal(readLocal(),remote);writeLocal(merged);refreshUI();await pushState(merged,remote);lastSnapshot=localStorage.getItem(STORAGE_KEY)||JSON.stringify(merged);setStatus('☁ Synced','ok');window.dispatchEvent(new CustomEvent('language-lab-cloud-synced',{detail:{reason,userId:user.id}}));}catch(error){console.warn('[Language Lab Free] Cloud sync failed:',error);setStatus(navigator.onLine?'☁ Sync pending':'Offline · saved locally','error');}finally{syncing=false;if(queued)setTimeout(()=>sync('queued'),250);}}
  function watchLocal(){clearInterval(timer);lastSnapshot=localStorage.getItem(STORAGE_KEY)||'';timer=setInterval(()=>{if(!user)return;const now=localStorage.getItem(STORAGE_KEY)||'';if(now!==lastSnapshot){lastSnapshot=now;sync('local-change');}},1200);}
  async function start(nextUser){user=nextUser||null;if(!user){clearInterval(timer);timer=null;initializedFor=null;setStatus('Guest · this device','');return;}if(initializedFor===user.id)return;initializedFor=user.id;setStatus('⟳ Loading cloud','busy');await sync('sign-in');watchLocal();}
  window.addEventListener('language-lab-auth-changed',e=>start(e.detail?.user||null));window.addEventListener('online',()=>{if(user)sync('online')});window.addEventListener('offline',()=>setStatus(user?'Offline · saved locally':'Guest · this device','error'));window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&user)sync('other-tab')});
  function init(){injectStyle();start(window.LanguageLabAuth?.getUser?.()||null);}
  window.LanguageLabCloudSync={sync:()=>sync('manual'),status:()=>({signedIn:Boolean(user),syncing,userId:user?.id||null})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
