// Language Lab Free — V10 account onboarding
(function(){
  const cloud=window.LANGUAGE_LAB_SUPABASE||{},client=cloud.client||null,Store=window.LanguageLabStorage,Core=window.LanguageLabCore||{};
  let user=null,selectedLanguage=null,audioPreference='auto',busy=false;
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalizeAudio=v=>Core.normalizeAudio?Core.normalizeAudio(v):(['auto','female','male'].includes(v)?v:'auto');
  function injectStyles(){if($('onboardingStyles'))return;const s=document.createElement('style');s.id='onboardingStyles';s.textContent=`.ll-onboard{position:fixed;inset:0;z-index:300;background:rgba(15,23,42,.82);display:grid;place-items:center;padding:18px;backdrop-filter:blur(8px)}.ll-onboard.hidden{display:none}.ll-onboard-card{width:min(760px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:24px;box-shadow:0 30px 80px rgba(0,0,0,.28)}.ll-onboard-head h2{margin:5px 0 7px}.ll-onboard-head p{margin:0;color:#64748b}.ll-onboard-step{margin-top:22px}.ll-onboard-step h3{margin:0 0 10px}.ll-language-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.ll-language{border:1px solid #dbe4f0;background:#fff;border-radius:14px;padding:12px 8px;text-align:center;min-height:78px}.ll-language span{display:block;font-size:25px}.ll-language b{display:block;font-size:12px;margin-top:5px}.ll-language.active,.ll-voice.active{border-color:#0f172a;background:#f1f5f9;box-shadow:inset 0 0 0 1px #0f172a}.ll-voice-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.ll-voice{border:1px solid #dbe4f0;background:#fff;border-radius:14px;padding:14px;text-align:left}.ll-voice strong,.ll-voice small{display:block}.ll-voice small{color:#64748b;margin-top:4px}.ll-onboard-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:22px}.ll-onboard-status{font-size:12px;color:#64748b;min-height:18px}.ll-onboard-actions button{min-width:160px}.ll-onboard-note{font-size:12px;color:#64748b;margin-top:8px}@media(max-width:720px),(pointer:coarse) and (max-width:1200px){.ll-onboard{padding:0;align-items:end}.ll-onboard-card{border-radius:24px 24px 0 0;max-height:94vh;padding:20px 16px}.ll-language-grid{grid-template-columns:repeat(2,1fr)}.ll-voice-grid{grid-template-columns:1fr}.ll-onboard-actions{align-items:stretch;flex-direction:column-reverse}.ll-onboard-actions button{width:100%;min-height:48px}}`;document.head.appendChild(s)}
  function ensureUI(){if($('llOnboarding'))return;const wrap=document.createElement('div');wrap.id='llOnboarding';wrap.className='ll-onboard hidden';wrap.innerHTML=`<section class="ll-onboard-card" role="dialog" aria-modal="true" aria-labelledby="llOnboardTitle"><div class="ll-onboard-head"><span class="eyebrow">Set up your learning</span><h2 id="llOnboardTitle">What do you want to learn?</h2><p>Choose your main language and preferred audio voice. Your home starts with only this course.</p></div><section class="ll-onboard-step"><h3>1. Choose your learning language</h3><div id="llOnboardLanguages" class="ll-language-grid"></div></section><section class="ll-onboard-step"><h3>2. Choose audio preference</h3><div class="ll-voice-grid"><button class="ll-voice" data-audio="auto"><strong>🔊 Auto</strong><small>Best matching device voice.</small></button><button class="ll-voice" data-audio="female"><strong>♀ Female preferred</strong><small>Prefer an identifiable female voice when available.</small></button><button class="ll-voice" data-audio="male"><strong>♂ Male preferred</strong><small>Prefer an identifiable male voice when available.</small></button></div><p class="ll-onboard-note">Voice gender is best-effort because browsers do not reliably expose gender metadata. Exact installed voice can still be selected in Listen & Speak.</p></section><div class="ll-onboard-actions"><span id="llOnboardStatus" class="ll-onboard-status"></span><button id="llOnboardSave" class="primary" type="button">Start learning</button></div></section>`;document.body.appendChild(wrap);$('llOnboardSave').onclick=save;wrap.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>{audioPreference=b.dataset.audio;renderAudio()})}
  function renderLanguages(){const host=$('llOnboardLanguages');if(!host)return;host.innerHTML=LANGUAGES.map(l=>`<button type="button" class="ll-language ${l.id===selectedLanguage?'active':''}" data-onboard-lang="${l.id}"><span>${esc(l.flag)}</span><b>${esc(l.name)}</b></button>`).join('');host.querySelectorAll('[data-onboard-lang]').forEach(b=>b.onclick=()=>{selectedLanguage=b.dataset.onboardLang;renderLanguages();previewLanguage()})}
  function renderAudio(){$('llOnboarding')?.querySelectorAll('[data-audio]').forEach(b=>b.classList.toggle('active',b.dataset.audio===audioPreference))}
  function setStatus(t){if($('llOnboardStatus'))$('llOnboardStatus').textContent=t||''}
  function previewLanguage(){const l=LANGUAGES.find(x=>x.id===selectedLanguage);if(!l||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(l.culturePhrase||l.vocab?.[0]?.native||l.name);u.lang=l.locale;u.rate=.8;speechSynthesis.speak(u)}catch{}}
  function saveVoicePref(){const raw=localStorage.getItem('languageLabV8VoicePrefs');let p={};try{p=raw?JSON.parse(raw):{}}catch{}p[selectedLanguage]=p[selectedLanguage]||{};p[selectedLanguage].gender=audioPreference;delete p[selectedLanguage].voice;localStorage.setItem('languageLabV8VoicePrefs',JSON.stringify(p));Store?.persistLegacyKey?.('languageLabV8VoicePrefs')}
  function applyAccountPreferences(data){const primary=data?.selected_language||'ja',enabled=Core.normalizeEnabledLanguages?Core.normalizeEnabledLanguages(data?.enabled_languages,primary,LANGUAGES.map(l=>l.id)):[primary],s=Store?.readState?.()||{};s.primaryLanguage=primary;s.enabledLanguages=enabled;s.selected=enabled.includes(s.selected)?s.selected:primary;s.audioPreference=normalizeAudio(data?.audio_preference);s.onboardingCompleted=true;s.profilePrefsUpdatedAt=data?.updated_at||s.profilePrefsUpdatedAt||null;Store?.writeState?.(s);audioPreference=s.audioPreference;selectedLanguage=primary;saveVoicePref();setTimeout(()=>{try{renderLanguages?.();renderTop?.()}catch{}},0)}
  async function save(){if(busy||!user||!selectedLanguage)return;busy=true;const btn=$('llOnboardSave');if(btn){btn.disabled=true;btn.textContent='Saving…'}setStatus('Saving your learning preferences…');try{const now=new Date().toISOString(),s=Store?.readState?.()||{};s.selected=selectedLanguage;s.primaryLanguage=selectedLanguage;s.enabledLanguages=[selectedLanguage];s.audioPreference=normalizeAudio(audioPreference);s.onboardingCompleted=true;s.profilePrefsUpdatedAt=now;Store?.writeState?.(s);saveVoicePref();if(client){const {data,error}=await client.from('profiles').update({selected_language:selectedLanguage,enabled_languages:[selectedLanguage],audio_preference:s.audioPreference,onboarding_completed:true}).eq('id',user.id).select('updated_at').maybeSingle();if(error)throw error;if(data?.updated_at){s.profilePrefsUpdatedAt=data.updated_at;Store?.writeState?.(s)}}$('llOnboarding')?.classList.add('hidden');window.dispatchEvent(new CustomEvent('language-lab-onboarding-complete',{detail:{language:selectedLanguage,enabledLanguages:[selectedLanguage],audioPreference:s.audioPreference}}));await window.LanguageLabCloudSync?.sync?.();}catch(e){console.warn('[Language Lab Free] onboarding save failed',e);setStatus('Could not save yet. Please try again.')}finally{busy=false;if(btn){btn.disabled=false;btn.textContent='Start learning'}}}
  async function check(nextUser){user=nextUser||null;if(!user){$('llOnboarding')?.classList.add('hidden');return}if(!client)return;try{const {data,error}=await client.from('profiles').select('selected_language,enabled_languages,audio_preference,onboarding_completed,updated_at').eq('id',user.id).maybeSingle();if(error)throw error;if(data?.onboarding_completed){applyAccountPreferences(data);$('llOnboarding')?.classList.add('hidden');return}const s=Store?.readState?.()||{};selectedLanguage=data?.selected_language||s.primaryLanguage||s.selected||'ja';audioPreference=normalizeAudio(data?.audio_preference||s.audioPreference);ensureUI();renderLanguages();renderAudio();setStatus('');$('llOnboarding').classList.remove('hidden')}catch(e){console.warn('[Language Lab Free] onboarding check skipped',e)}}
  function init(){injectStyles();ensureUI();window.addEventListener('language-lab-auth-changed',e=>check(e.detail?.user||null));const u=window.LanguageLabAuth?.getUser?.();if(u)check(u)}
  window.LanguageLabOnboarding={check};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
