// Language Lab Free — first-login onboarding for learning language + audio preference
(function(){
  const cloud=window.LANGUAGE_LAB_SUPABASE||{};
  const client=cloud.client||null;
  const VOICE_PREF_KEY='languageLabV8VoicePrefs';
  let user=null,selectedLanguage=null,audioPreference='auto',busy=false;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function injectStyles(){if($('onboardingStyles'))return;const s=document.createElement('style');s.id='onboardingStyles';s.textContent=`
  .ll-onboard{position:fixed;inset:0;z-index:300;background:rgba(15,23,42,.82);display:grid;place-items:center;padding:18px;backdrop-filter:blur(8px)}.ll-onboard.hidden{display:none}.ll-onboard-card{width:min(760px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:24px;box-shadow:0 30px 80px rgba(0,0,0,.28)}.ll-onboard-head h2{margin:5px 0 7px}.ll-onboard-head p{margin:0;color:#64748b}.ll-onboard-step{margin-top:22px}.ll-onboard-step h3{margin:0 0 10px}.ll-language-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.ll-language{border:1px solid #dbe4f0;background:#fff;border-radius:14px;padding:12px 8px;text-align:center;min-height:78px}.ll-language span{display:block;font-size:25px}.ll-language b{display:block;font-size:12px;margin-top:5px}.ll-language.active{border-color:#0f172a;background:#f1f5f9;box-shadow:inset 0 0 0 1px #0f172a}.ll-voice-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.ll-voice{border:1px solid #dbe4f0;background:#fff;border-radius:14px;padding:14px;text-align:left}.ll-voice strong{display:block}.ll-voice small{display:block;color:#64748b;margin-top:4px}.ll-voice.active{border-color:#0f172a;background:#f1f5f9;box-shadow:inset 0 0 0 1px #0f172a}.ll-onboard-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:22px}.ll-onboard-status{font-size:12px;color:#64748b;min-height:18px}.ll-onboard-actions button{min-width:160px}.ll-onboard-note{font-size:12px;color:#64748b;margin-top:8px}@media(max-width:720px), (pointer:coarse) and (max-width:1200px){.ll-onboard{padding:0;align-items:end}.ll-onboard-card{border-radius:24px 24px 0 0;max-height:94vh;padding:20px 16px}.ll-language-grid{grid-template-columns:repeat(2,1fr)}.ll-voice-grid{grid-template-columns:1fr}.ll-onboard-actions{align-items:stretch;flex-direction:column-reverse}.ll-onboard-actions button{width:100%;min-height:48px}.ll-language{min-height:70px}}
  `;document.head.appendChild(s)}

  function ensureUI(){if($('llOnboarding'))return;const wrap=document.createElement('div');wrap.id='llOnboarding';wrap.className='ll-onboard hidden';wrap.innerHTML=`<section class="ll-onboard-card" role="dialog" aria-modal="true" aria-labelledby="llOnboardTitle"><div class="ll-onboard-head"><span class="eyebrow">Set up your learning</span><h2 id="llOnboardTitle">What do you want to learn?</h2><p>Choose your main language and preferred voice. Your home will show only this language until you add another one.</p></div><section class="ll-onboard-step"><h3>1. Choose your learning language</h3><div id="llOnboardLanguages" class="ll-language-grid"></div></section><section class="ll-onboard-step"><h3>2. Choose audio preference</h3><div class="ll-voice-grid"><button class="ll-voice" data-audio="auto"><strong>🔊 Auto</strong><small>Use the best matching voice on this device.</small></button><button class="ll-voice" data-audio="female"><strong>♀ Female preferred</strong><small>Prefer an identifiable female voice when available.</small></button><button class="ll-voice" data-audio="male"><strong>♂ Male preferred</strong><small>Prefer an identifiable male voice when available.</small></button></div><p class="ll-onboard-note">Voice gender depends on what your browser/phone exposes. Exact device voice can still be selected later in Listen & Speak.</p></section><div class="ll-onboard-actions"><span id="llOnboardStatus" class="ll-onboard-status"></span><button id="llOnboardSave" class="primary" type="button">Start learning</button></div></section>`;document.body.appendChild(wrap);$('llOnboardSave').onclick=save;wrap.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>{audioPreference=b.dataset.audio;renderAudio()})}

  function renderLanguages(){const host=$('llOnboardLanguages');if(!host)return;host.innerHTML=LANGUAGES.map(l=>`<button type="button" class="ll-language ${l.id===selectedLanguage?'active':''}" data-onboard-lang="${l.id}"><span>${esc(l.flag)}</span><b>${esc(l.name)}</b></button>`).join('');host.querySelectorAll('[data-onboard-lang]').forEach(b=>b.onclick=()=>{selectedLanguage=b.dataset.onboardLang;renderLanguages();previewLanguage()})}
  function renderAudio(){$('llOnboarding')?.querySelectorAll('[data-audio]').forEach(b=>b.classList.toggle('active',b.dataset.audio===audioPreference))}
  function setStatus(t){if($('llOnboardStatus'))$('llOnboardStatus').textContent=t||''}

  function previewLanguage(){const l=LANGUAGES.find(x=>x.id===selectedLanguage);if(!l||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(l.culturePhrase||l.vocab?.[0]?.native||l.name);u.lang=l.locale;u.rate=.8;speechSynthesis.speak(u)}catch{}}

  function saveLocalVoice(){const p=(()=>{try{return JSON.parse(localStorage.getItem(VOICE_PREF_KEY)||'{}')}catch{return {}}})();p[selectedLanguage]=p[selectedLanguage]||{};p[selectedLanguage].gender=audioPreference;localStorage.setItem(VOICE_PREF_KEY,JSON.stringify(p))}
  function saveLocalLanguage(enabledLanguages=[selectedLanguage]){try{const s=JSON.parse(localStorage.getItem('languageLabFreeV3')||'{}')||{};s.selected=selectedLanguage;s.enabledLanguages=[...new Set((enabledLanguages||[]).filter(Boolean))];if(!s.enabledLanguages.length)s.enabledLanguages=[selectedLanguage];s.languages=s.languages||{};localStorage.setItem('languageLabFreeV3',JSON.stringify(s));if(typeof state!=='undefined'){state.selected=selectedLanguage;state.enabledLanguages=s.enabledLanguages}}catch{}}
  function applyAccountPreferences(data){selectedLanguage=data?.selected_language||selectedLanguage||'ja';audioPreference=['auto','female','male'].includes(data?.audio_preference)?data.audio_preference:'auto';const enabled=Array.isArray(data?.enabled_languages)&&data.enabled_languages.length?data.enabled_languages:[selectedLanguage];saveLocalLanguage(enabled);saveLocalVoice();setTimeout(()=>{try{if(typeof renderLanguages==='function')renderLanguages();if(typeof renderTop==='function')renderTop()}catch{}},0)}

  async function save(){if(busy||!user||!selectedLanguage)return;busy=true;const btn=$('llOnboardSave');if(btn){btn.disabled=true;btn.textContent='Saving…'}setStatus('Saving your learning preferences…');try{saveLocalLanguage([selectedLanguage]);saveLocalVoice();if(client){const {error}=await client.from('profiles').update({selected_language:selectedLanguage,enabled_languages:[selectedLanguage],audio_preference:audioPreference,onboarding_completed:true}).eq('id',user.id);if(error)throw error}window.LanguageLabCloudSync?.sync?.();$('llOnboarding')?.classList.add('hidden');window.dispatchEvent(new CustomEvent('language-lab-onboarding-complete',{detail:{language:selectedLanguage,enabledLanguages:[selectedLanguage],audioPreference}}));setTimeout(()=>{try{if(typeof renderLanguages==='function')renderLanguages();if(typeof renderTop==='function')renderTop()}catch{}},0)}catch(e){console.warn('[Language Lab Free] onboarding save failed',e);setStatus('Could not save yet. Please try again.')}finally{busy=false;if(btn){btn.disabled=false;btn.textContent='Start learning'}}}

  async function check(nextUser){user=nextUser||null;if(!user||!client)return;try{const {data,error}=await client.from('profiles').select('selected_language,enabled_languages,audio_preference,onboarding_completed').eq('id',user.id).maybeSingle();if(error)throw error;if(data?.onboarding_completed){applyAccountPreferences(data);return}selectedLanguage=data?.selected_language||(()=>{try{return JSON.parse(localStorage.getItem('languageLabFreeV3')||'{}').selected}catch{return null}})()||'ja';audioPreference=['auto','female','male'].includes(data?.audio_preference)?data.audio_preference:'auto';ensureUI();renderLanguages();renderAudio();setStatus('');$('llOnboarding').classList.remove('hidden')}catch(e){console.warn('[Language Lab Free] onboarding check skipped',e)}}

  function init(){injectStyles();ensureUI();window.addEventListener('language-lab-auth-changed',e=>check(e.detail?.user||null));const u=window.LanguageLabAuth?.getUser?.();if(u)check(u)}
  window.LanguageLabOnboarding={check};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();