// Language Lab Free — V10 skill model with mastery + coverage
(function(){
  const PREFIX='__v8skill__';
  const SKILLS=[
    {id:'listening',icon:'👂',label:'Listening',hint:'Hear and distinguish the target'},
    {id:'speaking',icon:'🎙️',label:'Speaking',hint:'Produce the target from memory'},
    {id:'recognition',icon:'👁️',label:'Recognition',hint:'Recognize form and meaning'},
    {id:'recall',icon:'🧠',label:'Recall',hint:'Retrieve meaning without prompts'},
    {id:'writing',icon:'✍️',label:'Writing',hint:'Reproduce the written form'}
  ];
  const relevant={listening:'all',speaking:'vocab',recognition:'vocab',recall:'vocab',writing:'items'};
  const $=id=>document.getElementById(id);
  function key(native,skill){return `${PREFIX}${skill}__${encodeURIComponent(native)}`}
  function store(langId){try{if(typeof state==='undefined')return null;if(!state.languages[langId])state.languages[langId]={mastery:{},writes:0,quizCorrect:0,quizTotal:0,favorites:[],xp:0};state.languages[langId].mastery=state.languages[langId].mastery||{};return state.languages[langId]}catch{return null}}
  function score(langId,native,skill){return Math.max(0,Math.min(100,Number(store(langId)?.mastery?.[key(native,skill)]||0)))}
  function add(langId,native,skill,amount){const st=store(langId);if(!st||!native)return 0;const k=key(native,skill),before=Number(st.mastery[k]||0),after=Math.min(100,before+Math.max(0,Number(amount||0)));if(after===before)return after;st.mastery[k]=after;try{save(true)}catch{window.LanguageLabStorage?.writeState?.(state)}renderSkillUI();return after}
  function targetsFor(l,skill){const items=l.units.flatMap(u=>u.items).map(x=>({native:x.native,roman:x.roman,type:'item'})),vocab=(l.vocab||[]).map(x=>({native:x.native,roman:x.roman,type:'vocab'})),raw=relevant[skill]==='items'?items:relevant[skill]==='vocab'?vocab:[...items,...vocab],seen=new Set();return raw.filter(x=>{if(seen.has(x.native))return false;seen.add(x.native);return true})}
  function stats(langId,skill){const l=LANGUAGES.find(x=>x.id===langId);if(!l)return{mastery:0,coverage:0,attempted:0,total:0,practiceAverage:0};const arr=targetsFor(l,skill),values=arr.map(x=>score(langId,x.native,skill)),attemptedValues=values.filter(v=>v>0),total=values.length,attempted=attemptedValues.length;return{mastery:total?Math.round(values.reduce((a,b)=>a+b,0)/total):0,coverage:total?Math.round(attempted/total*100):0,attempted,total,practiceAverage:attempted?Math.round(attemptedValues.reduce((a,b)=>a+b,0)/attempted):0}}
  function average(langId,skill){return stats(langId,skill).mastery}
  function itemAverage(langId,native){const l=LANGUAGES.find(x=>x.id===langId),st=store(langId);if(!l)return 0;const isItem=l.units.some(u=>u.items.some(i=>i.native===native)),isVocab=(l.vocab||[]).some(v=>v.native===native),ids=['listening',...(isVocab?['speaking','recognition','recall']:[]),...(isItem?['writing']:[])],values=ids.map(s=>score(langId,native,s)),hasSkill=values.some(v=>v>0);if(hasSkill)return Math.round(values.reduce((a,b)=>a+b,0)/(values.length||1));return Number(st?.mastery?.[native]||0)}
  function weakestSkill(langId){return SKILLS.map(s=>({...s,...stats(langId,s.id),value:average(langId,s.id)})).sort((a,b)=>a.value-b.value||a.coverage-b.coverage)[0]}
  function weakTarget(l,skill){return targetsFor(l,skill).sort((a,b)=>score(l.id,a.native,skill)-score(l.id,b.native,skill))[0]||null}
  function findItem(l,native){for(let ui=0;ui<l.units.length;ui++){const ii=l.units[ui].items.findIndex(x=>x.native===native);if(ii>=0)return{ui,ii}}return null}

  function injectStyles(){if($('v10SkillStyles'))return;const s=document.createElement('style');s.id='v10SkillStyles';s.textContent=`
  .v10-stage-nav{margin:12px 0 14px;padding:12px;border:1px solid #dbe4f0;border-radius:18px;background:#fff}.v10-stage-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:9px}.v10-stage-list{display:flex;gap:8px;overflow:auto}.v10-stage{min-width:145px;text-align:left;padding:9px 11px;border:1px solid #dbe4f0;border-radius:12px;background:#fff}.v10-stage small,.v10-stage b{display:block}.v10-stage small{margin-top:3px;color:#64748b}.v10-stage.active{border-color:#0f172a;background:#f8fafc}.v10-stage.planned{opacity:.55}.v10-skill-card{margin:14px 0;padding:18px;border:1px solid #dbe4f0;border-radius:18px;background:#fff}.v10-skill-title{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.v10-skill-title p{margin:4px 0 0}.v10-skill-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.v10-skill{border:1px solid #e2e8f0;border-radius:14px;padding:11px}.v10-skill strong,.v10-skill b,.v10-skill small{display:block}.v10-skill strong{font-size:20px}.v10-skill small{color:#64748b;margin:4px 0}.v10-skillbar{height:7px;background:#e2e8f0;border-radius:99px;overflow:hidden;margin:7px 0}.v10-skillbar span{display:block;height:100%;background:#0f172a}.v10-skill button{width:100%;border:1px solid #cbd5e1;background:#fff;border-radius:9px;padding:7px;font-weight:800}.v10-weak{font-size:12px;font-weight:800;padding:6px 9px;border-radius:99px;background:#fef3c7;color:#92400e;white-space:nowrap}.v10-item-skills{display:flex;flex-wrap:wrap;gap:6px;margin:9px 0}.v10-item-skill{font-size:11px;font-weight:800;padding:5px 7px;border-radius:99px;background:#f1f5f9;color:#475569}.v10-item-skill.trained{background:#ecfdf5;color:#166534}.v10-skill-note{margin-top:10px;font-size:11px;color:#64748b}@media(max-width:900px){.v10-skill-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.v10-skill-grid{grid-template-columns:1fr}.v10-stage-nav{margin-top:8px}}
  `;document.head.appendChild(s)}
  function stageForUnit(l,index){return l.curriculum?.stages?.find(s=>s.available&&index>=Number(s.startUnit||0)&&index<=Number(s.endUnit??l.units.length-1))||null}
  function renderStageNav(){const head=$('courseScreen')?.querySelector('.course-head');if(!head||typeof lang==='undefined')return;let box=$('v10StageNav');if(!box){box=document.createElement('section');box.id='v10StageNav';box.className='v10-stage-nav';head.insertAdjacentElement('afterend',box)}const stages=lang.curriculum?.stages||[];if(!stages.length){box.hidden=true;return}box.hidden=false;const current=stageForUnit(lang,Number(unitI||0));box.innerHTML=`<div class="v10-stage-head"><div><b>Learning path</b><small class="muted">${lang.id==='ja'||lang.id==='zh'?'Full staged curriculum available':'Foundation available; later stages are planned'}</small></div>${current?`<span class="badge">${current.label}</span>`:''}</div><div class="v10-stage-list">${stages.map(s=>`<button class="v10-stage ${s.available?'':'planned'} ${current?.id===s.id?'active':''}" data-v10-stage="${s.id}" ${s.available?'':'disabled'}><b>${s.label}</b><small>${s.description||''}</small></button>`).join('')}</div>`;box.querySelectorAll('[data-v10-stage]:not([disabled])').forEach(b=>b.onclick=()=>{const st=stages.find(x=>x.id===b.dataset.v10Stage);if(!st)return;unitI=Number(st.startUnit||0);itemI=0;renderUnit();$('unitSelect').value=unitI;document.querySelector('[data-tab="learn"]')?.click();renderStageNav()})}
  function renderItemSkills(){const focus=$('focusGuide');if(!focus||typeof lang==='undefined'||typeof curItem!=='function')return;let el=$('v10ItemSkills');if(!el){el=document.createElement('div');el.id='v10ItemSkills';el.className='v10-item-skills';focus.insertAdjacentElement('afterend',el)}const native=curItem().native;el.innerHTML=SKILLS.map(s=>{const v=score(lang.id,native,s.id);return`<span class="v10-item-skill ${v?'trained':''}" title="${s.hint}">${s.icon} ${v}%</span>`}).join('')}
  function renderSkillPanel(){const progress=$('progressTab'),anchor=progress?.querySelector('.stats-grid');if(!anchor||typeof lang==='undefined')return;let panel=$('v10SkillPanel');if(!panel){panel=document.createElement('article');panel.id='v10SkillPanel';panel.className='v10-skill-card';anchor.insertAdjacentElement('afterend',panel)}const wk=weakestSkill(lang.id),values=SKILLS.map(s=>({...s,...stats(lang.id,s.id)}));panel.innerHTML=`<div class="v10-skill-title"><div><span class="eyebrow">Skill profile</span><h3>Mastery + coverage</h3><p class="muted">A high score now requires progress across the course, not one successful item.</p></div><span class="v10-weak">Focus next: ${wk.icon} ${wk.label}</span></div><div class="v10-skill-grid">${values.map(s=>`<div class="v10-skill"><strong>${s.icon} ${s.mastery}%</strong><b>${s.label}</b><small>${s.hint}</small><div class="v10-skillbar"><span style="width:${s.mastery}%"></span></div><small>Coverage ${s.attempted}/${s.total} (${s.coverage}%)${s.attempted?` · practiced avg ${s.practiceAverage}%`:''}</small><button data-v10-practice="${s.id}">Practice weakest</button></div>`).join('')}</div><p class="v10-skill-note">Mastery includes unpracticed targets as zero. Coverage shows how much of the course you have actually attempted.</p>`;panel.querySelectorAll('[data-v10-practice]').forEach(b=>b.onclick=()=>practice(b.dataset.v10Practice))}
  function renderSkillUI(){try{renderStageNav();renderItemSkills();renderSkillPanel()}catch(e){console.debug('[Language Lab Free] skill UI refresh skipped',e)}}

  function practice(skill){if(typeof lang==='undefined')return;const target=weakTarget(lang,skill);if(!target)return;if(skill==='listening'||skill==='writing'){const pos=findItem(lang,target.native);if(pos){unitI=pos.ui;itemI=pos.ii;renderUnit()}document.querySelector(`[data-tab="${skill==='writing'?'write':'learn'}"]`)?.click();return}if(skill==='recognition'){const targetWord=lang.vocab.find(x=>x.native===target.native);document.querySelector('[data-tab="quiz"]')?.click();if(targetWord&&typeof quiz!=='undefined'&&typeof renderQuiz==='function'){const others=lang.vocab.filter(x=>x.native!==targetWord.native);quiz=[targetWord,...shuffle(others).slice(0,Math.min(9,others.length))];quizI=0;renderQuiz()}return}if(skill==='recall'){const i=lang.vocab.findIndex(x=>x.native===target.native);if(i>=0){cardOrder=lang.vocab.map((_,j)=>j);cardI=i;renderCard()}document.querySelector('[data-tab="cards"]')?.click();return}if(skill==='speaking'){const i=lang.vocab.findIndex(x=>x.native===target.native);if(i>=0){speakI=i;renderSpeak()}document.querySelector('[data-tab="speak"]')?.click()}}

  function hookPracticeEvents(){
    $('hearBtn')?.addEventListener('click',()=>setTimeout(()=>add(lang.id,curItem().native,'listening',6),0));
    $('slowBtn')?.addEventListener('click',()=>setTimeout(()=>add(lang.id,curItem().native,'listening',2),0));
    $('exampleBtn')?.addEventListener('click',()=>setTimeout(()=>add(lang.id,curItem().native,'listening',2),0));
    $('writeDoneBtn')?.addEventListener('click',()=>{const id=lang.id,native=curItem().native;setTimeout(()=>{if(($('writeFeedback')?.textContent||'').startsWith('Good'))add(id,native,'writing',12)},0)});
    document.addEventListener('click',e=>{const word=e.target.closest('[data-word]');if(word&&typeof lang!=='undefined'){const w=lang.vocab[Number(word.dataset.word)];if(w)add(lang.id,w.native,'listening',2)}const answer=e.target.closest('[data-answer]');if(answer&&typeof quiz!=='undefined'&&typeof quizI!=='undefined'&&!quizAnswered&&quiz[quizI]){const q=quiz[quizI],given=decodeURIComponent(answer.dataset.answer||'');if(given===q.meaning)setTimeout(()=>add(lang.id,q.native,'recognition',12),0)}},true);
    $('cardGood')?.addEventListener('click',()=>{try{const w=lang.vocab[cardOrder[cardI%cardOrder.length]];if(w)setTimeout(()=>add(lang.id,w.native,'recall',10),0)}catch{}},true);
    const match=$('matchText');if(match){let last='';new MutationObserver(()=>{const text=match.textContent||'';if(!/%$/.test(text)||text===last)return;last=text;const value=parseInt(text,10),w=lang?.vocab?.[speakI%lang.vocab.length];if(!Number.isFinite(value)||!w)return;add(lang.id,w.native,'speaking',value>=85?15:value>=60?8:2)}).observe(match,{childList:true,characterData:true,subtree:true})}
  }
  function wrapCoreRenders(){try{const base=renderUnit;renderUnit=function(){const r=base.apply(this,arguments);setTimeout(()=>{renderItemSkills();renderStageNav()},0);return r}}catch{}try{const base=renderProgress;renderProgress=function(){const r=base.apply(this,arguments);setTimeout(renderSkillPanel,0);return r}}catch{}try{const base=renderCourse;renderCourse=function(){const r=base.apply(this,arguments);setTimeout(renderSkillUI,0);return r}}catch{}}
  function init(){injectStyles();wrapCoreRenders();hookPracticeEvents();renderSkillUI();window.addEventListener('language-lab-cloud-synced',renderSkillUI);window.addEventListener('focus',renderSkillUI)}
  window.LanguageLabSkills={skills:SKILLS,score,add,stats,average,itemAverage,weakestSkill,weakTarget,render:renderSkillUI};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
