create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  native_language text,
  timezone text not null default 'UTC',
  total_xp integer not null default 0 check (total_xp >= 0),
  current_streak integer not null default 0 check (current_streak >= 0),
  longest_streak integer not null default 0 check (longest_streak >= 0),
  last_study_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.language_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  language_code text not null,
  current_unit integer not null default 0 check (current_unit >= 0),
  current_lesson integer not null default 0 check (current_lesson >= 0),
  mastery jsonb not null default '{}'::jsonb,
  favorites jsonb not null default '[]'::jsonb,
  writing_attempts integer not null default 0 check (writing_attempts >= 0),
  quiz_correct integer not null default 0 check (quiz_correct >= 0),
  quiz_total integer not null default 0 check (quiz_total >= 0),
  updated_at timestamptz not null default now(),
  unique(user_id, language_code)
);

create table if not exists public.study_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  xp_earned integer not null default 0 check (xp_earned >= 0),
  study_minutes integer not null default 0 check (study_minutes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, activity_date)
);

create index if not exists language_progress_user_id_idx on public.language_progress(user_id);
create index if not exists study_activity_user_date_idx on public.study_activity(user_id, activity_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists language_progress_set_updated_at on public.language_progress;
create trigger language_progress_set_updated_at before update on public.language_progress
for each row execute function public.set_updated_at();

drop trigger if exists study_activity_set_updated_at on public.study_activity;
create trigger study_activity_set_updated_at before update on public.study_activity
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.language_progress enable row level security;
alter table public.study_activity enable row level security;

create policy "profiles_select_own" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "profiles_delete_own" on public.profiles for delete to authenticated using (auth.uid() = id);

create policy "language_progress_select_own" on public.language_progress for select to authenticated using (auth.uid() = user_id);
create policy "language_progress_insert_own" on public.language_progress for insert to authenticated with check (auth.uid() = user_id);
create policy "language_progress_update_own" on public.language_progress for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "language_progress_delete_own" on public.language_progress for delete to authenticated using (auth.uid() = user_id);

create policy "study_activity_select_own" on public.study_activity for select to authenticated using (auth.uid() = user_id);
create policy "study_activity_insert_own" on public.study_activity for insert to authenticated with check (auth.uid() = user_id);
create policy "study_activity_update_own" on public.study_activity for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "study_activity_delete_own" on public.study_activity for delete to authenticated using (auth.uid() = user_id);
